### ISSUE TITLE
Choose different name?

### ISSUE THREAD

**Issue by jobovy** [webbjj/nbodypy#1]
Great to see this package! But there is already a well-established ``pynbody`` package for analyzing collisionless (+hydro etc.) simulations: https://github.com/pynbody/pynbody (for example used in ``galpy`` to deal with simulations). So perhaps it would be better to change the name of this package to avoid name conflicts?

**Comment by webbjj** [comment]
Hi Jo

Thanks for the heads up. Yeah its just been something I have been
developing for personal use, and I figured id throw it on github so I can
easily upload/update it on yngve or something. But you are right that if
its going to be used elsewhere I should rename it. It also needs loads of
documentation still!

Will have to think.

Jeremy
